### ISSUE TITLE
win_dsc: Changing service path fails

### ISSUE THREAD

**Issue by rifftual** [ansible-collections/ansible.windows#140] opened 2020-11-27 16:02 UTC
##### SUMMARY
The module win_dsc fails to update/replace a service when the command path is changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`win_dsc`

##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/share/virtualenvs/assetindex-downloader-UTR8P2J9/lib/python3.8/site-packages/ansible
  executable location = /home/xxx/.local/share/virtualenvs/assetindex-downloader-UTR8P2J9/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION
Defaults only

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

##### STEPS TO REPRODUCE

```yaml
- name: Install the service
  win_dsc:
    resource_name: Service
    Ensure: Present
    Name: foo
    StartupType: Automatic
    State: Running
    Path: C:\Foo\Bar.exe
    Credential_username: foo
    Credential_password: bar
```

##### EXPECTED RESULTS
The service would be updated. Works with using DSC via PowerShell

##### ACTUAL RESULTS
```
fatal: [devopstest16.rmd.remedy.fi]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "BuiltInAccount": null,
            "Credential_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "Credential_username": "foo",
            "Dependencies": null,
            "DependsOn": null,
            "Description": null,
            "DisplayName": null,
            "Ensure": "Present",
            "Name": "foor",
            "Path": "C:\Foo\Bar.exe",
            "PsDscRunAsCredential_password": null,
            "PsDscRunAsCredential_username": null,
            "StartupType": "Automatic",
            "State": "Running",
            "module_version": "latest",
            "resource_name": "Service"
        }
    },
    "module_version": "1.1",
    "msg": "Failed to invoke DSC Set method: PowerShell DSC resource MSFT_ServiceResource  failed to execute Set-TargetResource functionality with error message: The service 'assetindex-downloader' to create already exists ",
    "reboot_required": false,
    "verbose_set": [
        "Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.",
        "An LCM method call arrived from computer FOO with user sid S-X-X-XX-XXX-XXX-XXX-XXX.",
        "[FOO]: LCM:  [ Start  Set      ]  [[Service]DirectResourceAccess]",
        "[FOO]:                            [[Service]DirectResourceAccess] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\\cimv2,'className' = win32_service'.",
        "[FOO]:                            [[Service]DirectResourceAccess] Operation 'Enumerate CimInstances' complete.",
        "[FOO]: LCM:  [ End    Set      ]  [[Service]DirectResourceAccess]  in 0.3750 seconds.",
        "Operation 'Invoke CimMethod' complete.",
        "Time taken for configuration job to complete is 0.616 seconds"
    ],
    "verbose_test": [
        "Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceTest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.",
        "An LCM method call arrived from computer FOO with user sidS-X-X-XX-XXX-XXX-XXX-XXX.",
        "[DEVOPSTEST16]: LCM:  [ Start  Test     ]  [[Service]DirectResourceAccess]",
        "[DEVOPSTEST16]:                            [[Service]DirectResourceAccess] Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\\cimv2,'className' = win32_service'.",
        "[DEVOPSTEST16]:                            [[Service]DirectResourceAccess] Operation 'Enumerate CimInstances' complete.",
        "[DEVOPSTEST16]: LCM:  [ End    Test     ]  [[Service]DirectResourceAccess] False in 0.5000 seconds.",
        "[DEVOPSTEST16]: LCM:  [ End    Set      ]    in  0.6090 seconds.",
        "Operation 'Invoke CimMethod' complete.",
        "Time taken for configuration job to complete is 0.775 seconds"
    ]
}
```

**Comment by jborean93** [comment] 2020-11-27 20:37
There’s nothing Ansible can do here, it’s calling the DSC resource with the parameters you’ve specified and it’s failing. This is either a bug on the `Service` resource or it’s working as intended from its perspective.

You will have to file a bug on that resource wherever it lives. I’m not sure where that is but it will be in some Microsoft repository.

Any reason why you can’t just use `win_service` for this task. It doesn’t rely on DSC and it should work for what you want to do as the unique identifier is the `name` option.

**Closed by jborean93** 2020-11-27 20:37 UTC

**Comment by rifftual** [comment] 2020-12-01 12:17
Thanks. Created an issue : PowerShell/PSDscResources#197
