### ISSUE TITLE
ansible.windows.win_command: Exception calling \"CreateProcess\" with \"6\" argument(s): \"CreateProcessW() failed (The file cannot be accessed by the system, Win32ErrorCode 1920)\"

### ISSUE THREAD

**Issue by vikekh** [ansible-collections/ansible.windows#232] opened 2021-06-06 13:13 UTC
##### SUMMARY
I am trying to run an installed executable with `ansible.windows.win_command`, but I am getting:

```
fatal: [desktop]: FAILED! => {
    "changed": false,
    "cmd": "winget install --id=Microsoft.VisualStudio.2019.Community -e",
    "msg": "Exception calling \"CreateProcess\" with \"6\" argument(s): \"CreateProcessW() failed (The file cannot be accessed by the system, Win32ErrorCode 1920)\"",
    "rc": 2
}
```

I wanted to try and use WinGet instead of Chocolatey and until there is module support for it I'd thought I would try `win_command`, but I get this, for me, cryptic error.

I tried to do the suggestions [here](https://github.com/ansible/ansible/issues/66724):

`- raw: C:\Windows\System32\cmd.exe /c set`:

```
changed: [desktop] => {
    "changed": true,
    "rc": 0,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "ALLUSERSPROFILE=C:\\ProgramData\r\nAMDRMPATH=C:\\Program Files\\AMD\\RyzenMaster\\\r\nAPPDATA=C:\\Users\\Viktor\\AppData\\Roaming\r\nc28fc6f98a2c44abbbd89d6a3037d0d9_POSIX_FD_STATE=AAAAAAICAgA=\r\nChocolateyInstall=C:\\ProgramData\\chocolatey\r\nChocolateyLastPathUpdate=132593324000071309\r\nCommonProgramFiles=C:\\Program Files\\Common Files\r\nCommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files\r\nCommonProgramW6432=C:\\Program Files\\Common Files\r\nCOMPUTERNAME=SPIROU2\r\nComSpec=C:\\WINDOWS\\system32\\cmd.exe\r\nDriverData=C:\\Windows\\System32\\Drivers\\DriverData\r\nHOME=C:\\Users\\Viktor\r\nHOMEDRIVE=C:\r\nHOMEPATH=\\Users\\Viktor\r\nLOCALAPPDATA=C:\\Users\\Viktor\\AppData\\Local\r\nLOGNAME=viktor\r\nNUMBER_OF_PROCESSORS=12\r\nOneDrive=C:\\Users\\Viktor\\OneDrive\r\nOneDriveConsumer=C:\\Users\\Viktor\\OneDrive\r\nOS=Windows_NT\r\nPath=C:\\Program Files\\OpenSSH;C:\\Program Files\\AdoptOpenJDK\\jre-16.0.1.9-hotspot\\bin;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\AdoptOpenJDK\\jre-15.0.2.7-hotspot\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\WireGuard\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Viktor\\scoop\\shims;C:\\Users\\Viktor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Viktor\\.dotnet\\tools;C:\\Program Files\\kdiff3;C:\\Users\\Viktor\\.dotnet\\tools;C:\\Users\\Viktor\\AppData\\Roaming\\npm\r\nPATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL\r\nPROCESSOR_ARCHITECTURE=AMD64\r\nPROCESSOR_IDENTIFIER=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD\r\nPROCESSOR_LEVEL=25\r\nPROCESSOR_REVISION=2100\r\nProgramData=C:\\ProgramData\r\nProgramFiles=C:\\Program Files\r\nProgramFiles(x86)=C:\\Program Files (x86)\r\nProgramW6432=C:\\Program Files\r\nPROMPT=viktor@SPIROU2 $P$G\r\nPSExecutionPolicyPreference=Unrestricted\r\nPSModulePath=C:\\Users\\Viktor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\r\nPUBLIC=C:\\Users\\Public\r\nSHELL=c:\\windows\\system32\\cmd.exe\r\nSSH_CLIENT=172.26.24.81 59182 22\r\nSSH_CONNECTION=172.26.24.81 59182 172.26.16.1 22\r\nSystemDrive=C:\r\nSystemRoot=C:\\WINDOWS\r\nTEMP=C:\\Users\\Viktor\\AppData\\Local\\Temp\r\nTMP=C:\\Users\\Viktor\\AppData\\Local\\Temp\r\nUSER=viktor\r\nUSERDOMAIN=WORKGROUP\r\nUSERNAME=viktor\r\nUSERPROFILE=C:\\Users\\Viktor\r\nwindir=C:\\WINDOWS\r\n",
    "stdout_lines": [
        "ALLUSERSPROFILE=C:\\ProgramData",
        "AMDRMPATH=C:\\Program Files\\AMD\\RyzenMaster\\",
        "APPDATA=C:\\Users\\Viktor\\AppData\\Roaming",
        "c28fc6f98a2c44abbbd89d6a3037d0d9_POSIX_FD_STATE=AAAAAAICAgA=",
        "ChocolateyInstall=C:\\ProgramData\\chocolatey",
        "ChocolateyLastPathUpdate=132593324000071309",
        "CommonProgramFiles=C:\\Program Files\\Common Files",
        "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files",
        "CommonProgramW6432=C:\\Program Files\\Common Files",
        "COMPUTERNAME=SPIROU2",
        "ComSpec=C:\\WINDOWS\\system32\\cmd.exe",
        "DriverData=C:\\Windows\\System32\\Drivers\\DriverData",
        "HOME=C:\\Users\\Viktor",
        "HOMEDRIVE=C:",
        "HOMEPATH=\\Users\\Viktor",
        "LOCALAPPDATA=C:\\Users\\Viktor\\AppData\\Local",
        "LOGNAME=viktor",
        "NUMBER_OF_PROCESSORS=12",
        "OneDrive=C:\\Users\\Viktor\\OneDrive",
        "OneDriveConsumer=C:\\Users\\Viktor\\OneDrive",
        "OS=Windows_NT",
        "Path=C:\\Program Files\\OpenSSH;C:\\Program Files\\AdoptOpenJDK\\jre-16.0.1.9-hotspot\\bin;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\AdoptOpenJDK\\jre-15.0.2.7-hotspot\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\WireGuard\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\nodejs\\;C:\\WINDOWS\\system32\\config\\systemprofile\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Viktor\\scoop\\shims;C:\\Users\\Viktor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Viktor\\.dotnet\\tools;C:\\Program Files\\kdiff3;C:\\Users\\Viktor\\.dotnet\\tools;C:\\Users\\Viktor\\AppData\\Roaming\\npm",
        "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
        "PROCESSOR_ARCHITECTURE=AMD64",
        "PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD",
        "PROCESSOR_LEVEL=25",
        "PROCESSOR_REVISION=2100",
        "ProgramData=C:\\ProgramData",
        "ProgramFiles=C:\\Program Files",
        "ProgramFiles(x86)=C:\\Program Files (x86)",
        "ProgramW6432=C:\\Program Files",
        "PROMPT=viktor@SPIROU2 $P$G",
        "PSExecutionPolicyPreference=Unrestricted",
        "PSModulePath=C:\\Users\\Viktor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
        "PUBLIC=C:\\Users\\Public",
        "SHELL=c:\\windows\\system32\\cmd.exe",
        "SSH_CLIENT=172.26.24.81 59182 22",
        "SSH_CONNECTION=172.26.24.81 59182 172.26.16.1 22",
        "SystemDrive=C:",
        "SystemRoot=C:\\WINDOWS",
        "TEMP=C:\\Users\\Viktor\\AppData\\Local\\Temp",
        "TMP=C:\\Users\\Viktor\\AppData\\Local\\Temp",
        "USER=viktor",
        "USERDOMAIN=WORKGROUP",
        "USERNAME=viktor",
        "USERPROFILE=C:\\Users\\Viktor",
        "windir=C:\\WINDOWS"
    ]
}
```

[Custom module](https://github.com/ansible/ansible/issues/66724#issuecomment-578074988):

```
ok: [desktop] => {
    "changed": false,
    "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
}
```

Any ideas? Works fine from CMD or PowerShell on target machine. If I change value of `win_command` to `ipconfig` it works via Ansible.

Thank you in advance!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`ansible.windows.win_command`

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.1]
  config file = None
  configured module search path = ['/home/viktor/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/viktor/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/viktor/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/viktor/.local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
---

- hosts: all
  tasks:
    - ansible.windows.win_command: "winget install --id=Microsoft.VisualStudio.2019.Community -e"
```

##### EXPECTED RESULTS

Application gets installed like it does when I run it from CMD or PowerShell on target.

##### ACTUAL RESULTS

```paste below
fatal: [desktop]: FAILED! => {
    "changed": false,
    "cmd": "winget install --id=Microsoft.VisualStudio.2019.Community -e",
    "msg": "Exception calling \"CreateProcess\" with \"6\" argument(s): \"CreateProcessW() failed (The file cannot be accessed by the system, Win32ErrorCode 1920)\"",
    "rc": 2
}
```

**Comment by jborean93** [comment] 2021-06-08 05:36
Just transfered this issue to this repo as that's where the code actually lives. The error you are seeing is essentially [CreateProcess](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) failing with the error [ERROR_CANT_ACCESS_FILE](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/18d8fbe8-a967-4f1c-ae50-99ca8e491d2d). This is a bit different from a permissions, share violation, missing path like error you typically get. My guess is that `winget.exe` is on the `PATH` as an `AppExecLink` but not actually installed. An `AppExecLink` is like a symbolic link but has a few more smarts specific to Windows. One of the features is that it can point to a non-existent program and Windows will prompt you if you wish to install it.

To test out this theory can you run the following

```powershell
$winget = (Get-Command winget).Source

[IO.File]::GetAttributes($winget)

fsutil reparsepoint query $winget
```

If the file attributes contains `ReparsePoint` we can use the `fsutil` command to get more info. The output from `fsutil` will contain the reparse tag value as well as the raw tag buffer. An `AppExecLink` has a tag value of `0x8000001b`. If this is an `AppExecLink` then it's most likely you have actually installed winget so the target does not exist hence the error you receive back from Windows.

**Comment by vikekh** [comment] 2021-06-09 22:33
@jborean93 You are most correct. It is an `AppExecLink` which is a new term for me. Any ideas on how to deal with such installations from Ansible? Find the real path using the info in the link/blog and using that?

**Comment by jborean93** [comment] 2021-06-09 22:40
You should be able to invoke it from Ansible, the issue is `winget` isn't installed or at least isn't installed at the target of the `AppExecLink`. Because the target isn't present Windows is erroring with

> The file cannot be accessed by the system

It could also be that winget isn't installed for the current user in question. Would you be able to share the output of `fsutil` and the value of `$winget`?

**Comment by vikekh** [comment] 2021-06-10 10:11
@jborean93 Certainly!

```
PS C:\Users\Viktor> $winget = (Get-Command winget).Source
PS C:\Users\Viktor>
PS C:\Users\Viktor> [IO.File]::GetAttributes($winget)
Archive, ReparsePoint
PS C:\Users\Viktor>
PS C:\Users\Viktor> fsutil reparsepoint query $winget
Reparse Tag Value : 0x8000001b
Tag value: Microsoft

Reparse Data Length: 0x1a4
Reparse Data:
0000:  03 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  ....M.i.c.r.o.s.
0010:  6f 00 66 00 74 00 2e 00  44 00 65 00 73 00 6b 00  o.f.t...D.e.s.k.
0020:  74 00 6f 00 70 00 41 00  70 00 70 00 49 00 6e 00  t.o.p.A.p.p.I.n.
0030:  73 00 74 00 61 00 6c 00  6c 00 65 00 72 00 5f 00  s.t.a.l.l.e.r._.
0040:  38 00 77 00 65 00 6b 00  79 00 62 00 33 00 64 00  8.w.e.k.y.b.3.d.
0050:  38 00 62 00 62 00 77 00  65 00 00 00 4d 00 69 00  8.b.b.w.e...M.i.
0060:  63 00 72 00 6f 00 73 00  6f 00 66 00 74 00 2e 00  c.r.o.s.o.f.t...
0070:  44 00 65 00 73 00 6b 00  74 00 6f 00 70 00 41 00  D.e.s.k.t.o.p.A.
0080:  70 00 70 00 49 00 6e 00  73 00 74 00 61 00 6c 00  p.p.I.n.s.t.a.l.
0090:  6c 00 65 00 72 00 5f 00  38 00 77 00 65 00 6b 00  l.e.r._.8.w.e.k.
00a0:  79 00 62 00 33 00 64 00  38 00 62 00 62 00 77 00  y.b.3.d.8.b.b.w.
00b0:  65 00 21 00 77 00 69 00  6e 00 67 00 65 00 74 00  e.!.w.i.n.g.e.t.
00c0:  00 00 43 00 3a 00 5c 00  50 00 72 00 6f 00 67 00  ..C.:.\.P.r.o.g.
00d0:  72 00 61 00 6d 00 20 00  46 00 69 00 6c 00 65 00  r.a.m. .F.i.l.e.
00e0:  73 00 5c 00 57 00 69 00  6e 00 64 00 6f 00 77 00  s.\.W.i.n.d.o.w.
00f0:  73 00 41 00 70 00 70 00  73 00 5c 00 4d 00 69 00  s.A.p.p.s.\.M.i.
0100:  63 00 72 00 6f 00 73 00  6f 00 66 00 74 00 2e 00  c.r.o.s.o.f.t...
0110:  44 00 65 00 73 00 6b 00  74 00 6f 00 70 00 41 00  D.e.s.k.t.o.p.A.
0120:  70 00 70 00 49 00 6e 00  73 00 74 00 61 00 6c 00  p.p.I.n.s.t.a.l.
0130:  6c 00 65 00 72 00 5f 00  31 00 2e 00 31 00 31 00  l.e.r._.1...1.1.
0140:  2e 00 31 00 31 00 34 00  35 00 31 00 2e 00 30 00  ..1.1.4.5.1...0.
0150:  5f 00 78 00 36 00 34 00  5f 00 5f 00 38 00 77 00  _.x.6.4._._.8.w.
0160:  65 00 6b 00 79 00 62 00  33 00 64 00 38 00 62 00  e.k.y.b.3.d.8.b.
0170:  62 00 77 00 65 00 5c 00  41 00 70 00 70 00 49 00  b.w.e.\.A.p.p.I.
0180:  6e 00 73 00 74 00 61 00  6c 00 6c 00 65 00 72 00  n.s.t.a.l.l.e.r.
0190:  43 00 4c 00 49 00 2e 00  65 00 78 00 65 00 00 00  C.L.I...e.x.e...
01a0:  30 00 00 00                                       0...
PS C:\Users\Viktor> $winget
C:\Users\Viktor\AppData\Local\Microsoft\WindowsApps\winget.exe
```

**Comment by jborean93** [comment] 2021-06-10 20:43
Thanks for the info, when parsing that reparse buffer you essentially get these values

* Version: `3`
* Package ID: `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe`
* Entry Point: `Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget`
* Executable: `C:\Program Files\WindowsApps\MicrosoftDesktopAppInstaller_1.11.11451.0_x64__8wekyb3d8bbwe\AppInstallerCLI.exe`
* Application Type: `30 00 00 00`

So when `CreateProcess` sees the executable it has been asked to start is an `AppExecLink` it gets the value of `Executable` and invokes that instead. The `C:\Program Files\WindowsApps` folder is protected by default from even admin accounts and while you could overwrite the permissions I wouldn't recommend it as you might break UWP apps in general.

Essentially this `AppExecLink` is an alias to the [App Installer](https://www.microsoft.com/en-au/p/app-installer/9nblggh4nns1?ocid=9nblggh4nns1_ORSEARCH_Bing&rtc=2&activetab=pivot:overviewtab) package. You need to make sure that is already installed on your host before you try to run `winget` through Ansible.

Some more links that might be helpful

* https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/
* https://oofhours.com/2020/08/13/command-line-apps-from-the-store-how-does-that-work/

**Comment by jborean93** [comment] 2021-07-08 20:38
Closing this issue as I believe the above the fundamental problem and the current error is the expected result. When dealing with these links the target must be present or else Windows won't know what to do.

**Closed by jborean93** 2021-07-08 20:38 UTC
